config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :items
  resources :categories
  resources :images,	only: [ :create, :new, :destroy ]
  resources :comments,	only: [ :create, :new, :destroy ]
  resources :reviews
  resources :faqs
  resources :sessions,	only: [ :new, :destroy, :create ]

  resources :carts,		only: [ :create, :destroy, :index ]
  resources :orders,	only: [ :create, :destroy ]
  resources :bookmarks,	only: [ :create, :destroy, :index ]

  root 'items#catalog'

  match '/about',		to: 'static_pages#about',		via: 'get'
  match '/contacts',	to: 'static_pages#contacts',	via: 'get'
  match '/help',		to: 'static_pages#help',		via: 'get'
  match '/catalog',		to: 'items#catalog',			via: 'get'

  match '/signin',		to: 'sessions#new',				via: 'get'
  match '/signout',		to: 'sessions#destroy',			via: 'delete'
  match '/signup',		to: 'users#new',				via: 'get'

  get 'sessions/create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user
	belongs_to :item

	validates :item_id,	presence: true
	validates :user_id, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user,	class_name: 'User'
	belongs_to :item,	class_name: 'Item'

	validates :item_id,	presence: true
	validates :user_id,	presence: true
	validates :price,	presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items,		dependent: :destroy
	belongs_to :category 
	has_many :categories,	dependent: :destroy

	validates :name,	presence: true,	uniqueness: true
	validates :desc,	presence: true

	before_save { self.category_id ||= 0 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :item
	belongs_to :user
	
	validates :user_id,	presence: true
	validates :item_id,	presence: true
	validates :message,	presence: true
end

app/models/faq.rb
class Faq < ActiveRecord::Base
	validates :question,	presence: true, length: { in: 10...350 }
	validates :answer,		presence: true, length: { in: 10...350 }
end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :item

	has_attached_file :path, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :path, :content_type => /\Aimage\/.*\Z/

	# validates :path, presence: true, uniqueness: { case_sensitive: true }
	validates :title, presence: true
	validates :item_id,	presence: true

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :images,	dependent: :destroy
	has_many :comments,	dependent: :destroy
	has_many :bookmarks,	dependent: :destroy
	belongs_to	:category

	validates :name,	presence: true, length: { in: 3..25 }
	validates :desc,	presence: true
	validates :price,	presence: true
	validates :category_id,	presence: true

	def image
		# return Image.new(path: '/images/image-not-found.jpg', title: 'Not found')
		return self.images.first if self.images.any?
		return Image.new
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :item

	validates :item_id,	presence: true
	validates :user_id,	presence: true
	validates :price,	presence: true
	validates :count,	presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :carts,	dependent: :destroy
	has_many :orders,	dependent: :destroy
	has_many :bookmarks,	dependent: :destroy

	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	before_save { email.downcase! }
	before_create :create_remember_token

	validates :login, presence: true, length: { in: 3..50 }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	def in_cart?(item)
		carts.find { |x| x.item === item }
	end

	def cart_link(item)
		Cart.where(user_id: id, item_id: item.id).first
	end

	def in_orders?(item)
		orders.find { |x| x.item === item }
	end

	def order_link(item)
		Order.where(user_id: id, item_id: item.id).first
	end

	def in_bookmarks?(item)
		bookmarks.find { |x| x.item === item }
	end

	def bookmark_link(item)
		Bookmark.where(user_id: id, item_id: item.id).first
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	include CategoriesHelper

	before_action :get_filter, only: [ :catalog, :index ]

	def index
		@items = Item.paginate(page: params[:page])
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def create
		@item = Item.create(item_params)
		if @item.save
			flash[:success] = 'Item created.'
			redirect_to @item
		else
			flash.now[:error] = "Item don't created."
			render 'new'
		end
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update
		@item = Item.find(params[:id])
		if @item.update_attributes item_params
			flash[:success] = 'Item updated.'
			redirect_to @item 
		else
			flash.now[:error] = "Item don't updated."
			render 'edit'
		end
	end

	def destroy
		Item.find(params[:id]).destroy
		flash[:success] = 'Item removed.'
		redirect_to items_path
	end

	def catalog
		@items = Item.paginate(page: params[:page], per_page: 12)
	end

	private

		def get_filter
			current_user
		end

		def item_params
			params.require(:item).permit(:name, :articul, :desc, :price, :category_id)
		end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def cart_prices
		sum = 0
		current_user.carts.each do |x|
			sum += x.price
		end
		sum
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	def get_last_see
		Item.all[0..3]
	end

	def get_popular
		Item.all.sort { |x| x.bookmarks.count }[0..3]
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def review_object
		review = Review.find_by(user_id: current_user.id)
		if review.nil?
			Review.new
		else
			review 
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute :remember_token, User.encrypt(remember_token)
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.encrypt(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		current_user == user
	end

	def signed_in?
		!current_user.nil?
	end

	def admin?
		signed_in? && current_user.admin?
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url,	notice: 'Please sign in.'
		end
	end

	def sign_out
		current_user.update_attribute :remember_token, User.encrypt(User.new_remember_token)
		cookies.delete :remember_token
		self.current_user = nil
	end

	def auth_user
		redirect_to root_url if signed_in?
	end

	def admin_user
		redirect_to root_url unless admin?
	end

	def redirect_back_or(path)
		redirect_to(session[:return_to] || path)
		session.delete :return_to
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :articul %>
<%= f.number_field :articul %>
<%= f.label :category_id %>
<%= f.collection_select :category_id, Category.all, :id, :name %>
<%= f.label :price %>
<%= f.number_field :price %>
<%= f.label :desc %>
<%= f.text_area :desc %>

app/views/items/_filter.html.erb
<h3>Фильтр</h3>
<%= form_tag do %>
	<%= label_tag 'Имя' %>
	<%= text_field_tag :name %>
	<%= label_tag 'Цена' %>
	<%= submit_tag 'Применить' %>
	<%= link_to 'Сбросить', '#', class: 'btn' %>
<% end %>

app/views/items/_item.html.erb
<tr>
	<td><%= item.id %></td>
	<td><%= item.name %></td>
	<td><%= item.articul %></td>
	<td><%= item.price %></td>
	<td><%= link_to 'Просмотр', item %></td>
	<td><%= link_to 'Изменить', edit_item_path(item) %></td>
	<td><%= link_to 'Удалить', item, method: 'delete' %></td>
</tr>

app/views/items/_items.html.erb
<ul class="items">
	<% items.each do |x| %>
	<li>
		<img src="<%= x.image.path %>" alt="<%= x.image.title %>">
		<h4><%= link_to x.name, x %></h4>
		<b class="price"><%= x.price %></b>
		<%= link_to x.category.name, x.category, class: 'cat' %>
	</li>
	<% end %>
</ul>

app/views/items/catalog.html.erb
<% provide :title, 'Каталог' %>
<!-- <aside id="filter">
	<%#= render 'filter' %>
	<nav class="cat-nav">
		<%#= render 'categories/tree', root: get_root %>
	</nav>
</aside> -->
<div class="container">
	<%= will_paginate %>
	<%= render 'shared/catalog' %>
	<%= will_paginate %>
</div>

<!-- <aside id="right_bar">
	<div id="last_see">
		<h3>Последнее просмотренное</h3>
		<%#= render 'items', items: get_last_see %>
	</div>
	<div id="popular">
		<h3>Популярное</h3>
		<%#= render 'items', items: get_popular %>
	</div>
</aside> -->

app/views/items/edit.html.erb
<% provide :title, "Изменение #{@item.name}" %>
<div class="form">
	<%= form_for @item do |f| %>
		<%= render 'fields', f: f %>
		<%= f.submit 'Изменить' %>
	<% end %>
</div>

<div class="form form-inline">
	<%= form_for Image.new do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.text_field :title, placeholder: 'Заголовок' %>
		<%= f.file_field :path, placeholder: 'Изображение' %>
		<%= f.hidden_field :item_id, value: @item.id %>
		<%= f.submit 'Загрузить' %>
	<% end %>
</div>

<ul class="images">
	<h2>Изображения</h2>
	<% @item.images.each do |x| %>
	<li>
		<img src="<%= x.path.url(:thumb) %>" alt="<%= x.title %>">
		<%= link_to content_tag('i', '', class: 'fa fa-times'), x, method: 'delete' %>
	</li>
	<% end %>
</ul>

app/views/items/index.html.erb
<% provide :title, 'Items' %>
<h1>Items</h1>
<table class="table">
	<thead>
		<th>#</th>
		<th>Name</th>
		<th>Articul</th>
		<th>Price</th>
		<th colspan="3">Actions</th>
	</thead>
	<%= render @items %>
</table>
<%= link_to 'Create', new_item_path %>

app/views/items/new.html.erb
<% provide :title, 'Создание элемента' %>
<h1>Создать элемент</h1>
<div class="form">
	<%= form_for @item do |f| %>
		<%= render 'fields', f: f %>
		<%= f.submit 'Создать' %>
	<% end %>
</div>
	

app/views/items/show.html.erb
<% provide :title, @item.name %>
<h1><%= @item.name %></h1>
<small class="form"><%= link_to 'Изменить', edit_item_path(@item), class: 'btn' if admin? %></small>

<div class="row">
	<div id="images">
		<%= image_tag @item.image.path.url(:medium), 'data-full' => @item.image.path.url %>
		<% @item.images.each do |x| %>
			<%= image_tag x.path.url(:thumb), 'data-full' => x.path.url %>
		<% end %>
	</div>

	<div id="item-info">
		<div class="price"><%= @item.price %></div>
		<div class="description">
			<%= @item.desc %>
		</div>

		<div class="form">
			<% unless current_user.in_cart?(@item) %>
				<%= form_for Cart.new do |f| %>
					<%= f.hidden_field :item_id, value: @item.id %>
					<%= f.submit 'В корзину!', class: 'btn' %>
				<% end %>
			<% else %>
				<%= link_to 'Из корзины', current_user.cart_link(@item), method: 'delete', class: 'btn' %>
			<% end if signed_in? %>

			<% unless current_user.in_bookmarks? @item %>
				<%= form_for Bookmark.new do |f| %>
					<%= f.hidden_field :item_id, value: @item.id %>
					<%= f.submit 'В избранное' %>
				<% end %>
			<% else %>
				<%= link_to 'Из избранного', current_user.bookmark_link(@item), method: 'delete', class: 'btn' %>
			<% end if signed_in?  %>
		</div>
	</div>
</div>

<div class="form">
	<%= form_for Comment.new do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.text_area :message %>
		<%= f.hidden_field :item_id, value: @item.id %>
		<%= f.submit 'Отправить' %>
	<% end %>
</div>

<ul class="comments">
	<% @item.comments.each do |x| %>
	<li>
		<b><%= x.user.login %></b>
		<i><%= x.created_at %></i>
		<p><%= x.message %></p>
	</li>
	<% end %>
</ul>