config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :items
  resources :categories
  resources :images,	only: [ :create, :new, :destroy ]
  resources :comments,	only: [ :create, :new, :destroy ]
  resources :reviews
  resources :faqs
  resources :sessions,	only: [ :new, :destroy, :create ]

  resources :carts,		only: [ :create, :destroy, :index ]
  resources :orders,	only: [ :create, :destroy ]
  resources :bookmarks,	only: [ :create, :destroy, :index ]

  root 'items#catalog'

  match '/about',		to: 'static_pages#about',		via: 'get'
  match '/contacts',	to: 'static_pages#contacts',	via: 'get'
  match '/help',		to: 'static_pages#help',		via: 'get'
  match '/catalog',		to: 'items#catalog',			via: 'get'

  match '/signin',		to: 'sessions#new',				via: 'get'
  match '/signout',		to: 'sessions#destroy',			via: 'delete'
  match '/signup',		to: 'users#new',				via: 'get'

  get 'sessions/create'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
	belongs_to :user
	belongs_to :item

	validates :item_id,	presence: true
	validates :user_id, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user,	class_name: 'User'
	belongs_to :item,	class_name: 'Item'

	validates :item_id,	presence: true
	validates :user_id,	presence: true
	validates :price,	presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items,		dependent: :destroy
	belongs_to :category 
	has_many :categories,	dependent: :destroy

	validates :name,	presence: true,	uniqueness: true
	validates :desc,	presence: true

	before_save { self.category_id ||= 0 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :item
	belongs_to :user
	
	validates :user_id,	presence: true
	validates :item_id,	presence: true
	validates :message,	presence: true
end

app/models/faq.rb
class Faq < ActiveRecord::Base
	validates :question,	presence: true, length: { in: 10...350 }
	validates :answer,		presence: true, length: { in: 10...350 }
end

app/models/filter.rb
class Filter < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :item

	has_attached_file :path, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :path, :content_type => /\Aimage\/.*\Z/

	# validates :path, presence: true, uniqueness: { case_sensitive: true }
	validates :title, presence: true
	validates :item_id,	presence: true

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :images,	dependent: :destroy
	has_many :comments,	dependent: :destroy
	has_many :bookmarks,	dependent: :destroy
	belongs_to	:category

	validates :name,	presence: true, length: { in: 3..25 }
	validates :desc,	presence: true
	validates :price,	presence: true
	validates :category_id,	presence: true

	def image
		# return Image.new(path: '/images/image-not-found.jpg', title: 'Not found')
		return self.images.first if self.images.any?
		return Image.new
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :item

	validates :item_id,	presence: true
	validates :user_id,	presence: true
	validates :price,	presence: true
	validates :count,	presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_many :carts,	dependent: :destroy
	has_many :orders,	dependent: :destroy
	has_many :bookmarks,	dependent: :destroy

	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	before_save { email.downcase! }
	before_create :create_remember_token

	validates :login, presence: true, length: { in: 3..50 }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	def in_cart?(item)
		carts.find { |x| x.item === item }
	end

	def cart_link(item)
		Cart.where(user_id: id, item_id: item.id).first
	end

	def in_orders?(item)
		orders.find { |x| x.item === item }
	end

	def order_link(item)
		Order.where(user_id: id, item_id: item.id).first
	end

	def in_bookmarks?(item)
		bookmarks.find { |x| x.item === item }
	end

	def bookmark_link(item)
		Bookmark.where(user_id: id, item_id: item.id).first
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/helpers/carts_helper.rb
module CartsHelper
	def cart_prices
		sum = 0
		current_user.carts.each do |x|
			sum += x.price
		end
		sum
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
	def get_last_see
		Item.all[0..3]
	end

	def get_popular
		Item.all.sort { |x| x.bookmarks.count }[0..3]
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def review_object
		review = Review.find_by(user_id: current_user.id)
		if review.nil?
			Review.new
		else
			review 
		end
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="row">
	<ul>
		<h2><%= link_to 'Каталог',				catalog_path %></h2>
		<% get_root.each do |x| %>
		<li><%= link_to x.name, x %></li>
		<% end %>
	</ul>
	<ul>
		<h2>Магазин</h2>
		<li><%= link_to 'О нас', 				about_path %></li>
		<li><%= link_to 'Помощь', 				help_path %></li>
		<li><%= link_to 'Оплата',	'#' %></li>
		<li><%= link_to 'Доставка',	'#' %></li>
		<li><%= link_to 'Вопросы и ответы', 	faqs_path %></li>
		<li><%= link_to 'Отзывы', 				reviews_path %></li>
		<li><%= link_to 'Контакты', 			contacts_path %></li>
	</ul>
	<div>
		<h2>Понравился наш магазин?</h2>
		<h3>Поделитесь им с друзьми</h3>
		<ul class="social-links">
			<li><a href="#"><i class="fa fa-2x fa-vk"></i></a></li>
			<li><a href="#"><i class="fa fa-2x fa-facebook-square"></i></a></li>
			<li><a href="#"><i class="fa fa-2x fa-twitter-square"></i></a></li>
		</ul>
		<div class="form form-inline">
			<%= form_tag do %>
				<%= phone_field_tag :phone %>
				<%= submit_tag 'Заказать звонок' %>
			<% end %>
		</div>
		Создано <a href="http://voove.ru" id="dev">VooVe</a> <br>
		специально для ... 2015
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="row">
	<div id="nav-btn" class="mobile">Меню</div>
	<a href="/" id="logo">Stefany</a>
	<div id="phone"><i class="fa fa-mobile-phone"></i>+7(987)654-32-10</div>
	<% if signed_in? %>
		<div id="cart">
			<p>
				В вашей корзине <%= current_user.carts.count %> товара<br/> на сумму <span class="price"><%= cart_prices %> р</span>
			</p>
			<a href="<%= carts_path %>" class="shopping-cart">
				<i class="fa fa-shopping-cart"></i> Просмотреть
			</a>
		</div>
		<div id="user-info">
			<ul>
				<li>
					<i class="fa fa-user"></i>
					<%= link_to current_user.login,	user_path(current_user) %>
				</li>
				<li>
					<i class="fa fa-star"></i>
					<%= link_to "Избранное(#{current_user.bookmarks.count})", bookmarks_path %>
				</li>
				<li>
					<i class="fa fa-sign-out"></i>
					<%= link_to 'Выход',	signout_path, method: 'delete' %>
				</li>
			</ul>
		</div>
	<% else %>
		<div id="user-info">
			<ul>
				<li><%= link_to 'Вход',	signin_path %></li>
				<li><%= link_to 'Регистрация',	signup_path %></li>
			</ul>
		</div>
	<% end %>
</div>
<nav id="main-nav">
	<ul>
		<li><%= link_to 'Каталог', 			catalog_path %></li>
		<!-- <li><%#= link_to 'Блог',				'#' %></li> -->
		<li><%= link_to 'Помощь',			help_path %></li>
		<li><%= link_to 'Вопросы и ответы', faqs_path %></li>
		<li><%= link_to 'Отзывы',			reviews_path %></li>
		<li><%= link_to 'Контакты',			contacts_path %></li>
		<li><%= link_to 'О магазине',			about_path %></li>
	</ul>
</nav>
<div id="categories">
	<%= render 'categories/tree', root: get_root %>

	<!-- <li>
		<a href="#">Куклы</a>
		<ul class="inner">
			<li><a href="#">Керамические</a></li>
			<li><a href="#">Тряпочные</a></li>
		</ul>
	</li>
	<li><a href="#">Игрушки</a></li>
	<li><a href="#">Декор</a></li>
	<li><a href="#">Всё</a></li> -->
</div>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, user-scalable-no">
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<header id="main-header">
			<div class="container">
				<%= render 'layouts/header' %>
			</div>
		</header>
		<section id="main" class="hero">
			<div class="container">
				<ul id="alerts">
					<% flash.each do |key, value| %>
						<li class="alert alert-<%= key %>"><%= value %></li>
					<% end %>
				</ul>
				<%= yield %>
			</div>
		</section>
		<footer id="main-footer">
			<div class="container">		
				<%= render 'layouts/footer' %>
			</div>
		</footer>
	</body>
</html>

app/views/shared/_catalog.html.erb
<ul id="popular">
	<% @items.each do |x| %>
	<li>
		<div>
			<img data-full="<%= x.image.path.url %>" src="<%= x.image.path.url(:medium) %>" alt="<%= x.image.title %>"/>
			<h2><%= link_to x.name, x %></h2>
			<% if signed_in? %>
			<!-- <div class="form"> -->
				<% unless current_user.in_cart? x %>
					<%= form_for Cart.new do |f| %>
						<%= f.hidden_field :item_id, value: x.id %>
						<%= f.submit 'В корзину' %>
					<% end %>
				<% else %>
					<%= link_to 'Из корзины', current_user.cart_link(x), method: 'delete' %>
				<% end %>
				<% unless current_user.in_bookmarks? x %>
					<%= form_for Bookmark.new do |f| %>
						<%= f.hidden_field :item_id, value: x.id %>
						<%= f.submit 'В избранное' %>
					<% end %>
				<% else %>
					<%= link_to 'Из избранного', current_user.bookmark_link(x), method: 'delete' %>
				<% end %>
			<!-- </div> -->
			<% end %>
			<%#= link_to content_tag('i', class: 'fa fa-cart-arrow-down'), cart %>
			<b class="price"><%= x.price %></b>
			<%= link_to x.category.name, x.category, class: 'cat' %>
			<p><%= x.desc %></p>
		</div>
	</li>
	<% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>